"""Build factual asset contracts from the bundled, pinned symbolic binding plan."""
from pathlib import Path
import json
P=Path(__file__).resolve().parent
from semantic_controls import SCENE_STATES,RECORD_KEYS,FORBIDDEN

def write(n,o):(P/(n+'.json')).write_text(json.dumps(o,indent=2)+'\n')
plan=json.loads((P/'operation_binding_contract.json').read_text())
write('states',{'implementation':'local_review_and_display_metadata_only','scene_preview_states':sorted(SCENE_STATES),'all_preview_states_including_qualified_and_acquiring':'Illustrative labels only. No state certifies real preparation, age, qualification, safety, execution, observation, physics or success.','initial_review_state':'HOLD','allowed_review_actions':['select_view','preview_scene_state','attach_record_labels','request_review','request_safe_close','clear_record_labels'],'allowed_record_label_keys':sorted(RECORD_KEYS),'permanently_disabled_actions':sorted(FORBIDDEN),'physical_execution':False,'device_io':False,'evidence_verified':False,'safe_close_review_accessible_from_every_preview_state':True,'closed_service_objects':['patterning.sealed_face','chamber.closed_front_window','mechanics.front_guard','rheology.guard'],'required_external_guards':plan['guards'] if 'guards' in plan else sorted({g for b in plan['operation_bindings'] for g in b['guard_ids']})})
write('asset_metadata',{'title':'Wetting transitions: original static laboratory scene','asset_pack_id':'wetting_transition_scene_assets_v1','directory_slug':'wetting_scene_assets_v1','task_id':'wetting_transition_operations_v2','schema_version':'1.0','source':{'title':'Wetting transitions in droplet drying on soft materials','authors':['Julia Gerber','Tobias Lendenmann','Hadi Eghlidi','Thomas M. Schutzius','Dimos Poulikakos'],'journal':'Nature Communications 10, 4776 (2019)','doi':'10.1038/s41467-019-12093-w','url':'https://www.nature.com/articles/s41467-019-12093-w','source_license':'CC BY 4.0 subject to credit-line exceptions'},'original_geometry_license':'Apache-2.0','units':'m','native_editable':'geometry/wetting_lab.blend','portable':['geometry/wetting_lab.glb','geometry/wetting_dimension_references.glb'],'display_transforms':[{'root':'DISPLAY.WHOLE_SLIDE_20X','scale_factor':20,'uniform':True,'scale_applies_to':'diameter and layer thickness alike','physical_interaction':False},{'root':'DISPLAY.MICROSCOPY_CROP_1000X','scale_factor':1000,'uniform':True,'scale_applies_to':'microscopy patch, synthetic illustration and nominal layer thickness','physical_interaction':False}],'exact_source_dimensions':{'glass_slide_m':[.024,.024,.00017],'pdms_nominal_film_m':.000030,'cy_nominal_film_m':.000035},'source_dimensions_status':'Nominal references only, not verified tolerances; source requires independent metrology','authored_geometry':['bench','enclosures','fixtures','carriers','tool illustration','coupon placeholder','micro crop lateral dimensions','synthetic cap','synthetic lattice pitch and count'],'not_implemented':['live device control','robot motion','collision simulation','deformable matter','evaporation solver','image acquisition','optical physics','inverse FE solver','source-data reanalysis','real service authentication','scientific reproduction'],'hazard_boundary':'Patterning interface handles external qualified safe receipts only. No cadmium processing, quantum-dot preparation, ink handling or high-voltage patterning recipe or controls.','source_pixels_or_CAD_used':False,'physical_geometry_validated':False,'scientific_success':False,'validated_runnable_whole_paper_tasks':0})
write('variants',{'sample_variants':[{'id':'PDMS_9_1','family':'PDMS','nominal_film_m':.00003,'age_source_weeks':[1,3]},{'id':'PDMS_30_1','family':'PDMS','nominal_film_m':.00003,'age_source_weeks':[1,3],'microscopy_role':'dedicated resolution-limit branch'},{'id':'PDMS_50_1','family':'PDMS','nominal_film_m':.00003,'age_source_weeks':[1,3],'high_thickness_control':'220 versus 228 um held'},{'id':'CY_5_6','family':'CY','nominal_film_m':.000035,'age_source_weeks':[2,3]},{'id':'CY_9_10','family':'CY','nominal_film_m':.000035,'age_source_weeks':[2,3]}],'appearance_does_not_identify_material':True,'each_actual_sample_requires_independent_identity':True,'variants_are_metadata_not_new_measurement_instances':True,'coupon_dimensions':'unknown; authored placeholder not a qualified test specimen','patterned_variant':'external qualified receipt and containment required; no hazardous process model','droplets_not_substrates':'Cohort repeat counts do not establish independent physical substrate counts'})
write('review/source_comparison',{'status':'FACTUAL_ASSET_SCOPE_AUDIT','source_url':'https://www.nature.com/articles/s41467-019-12093-w','review_basis':'Reviewed full-paper requirements and paper-level route proposal; original asset design, not apparatus reconstruction','represented_source_geometry':[{'source':'E01 / main Methods','reference':'24 mm slide diameter; 0.17 mm glass; nominal 30 um PDMS and 35 um CY films','implementation':'Native metric source-reference solids; separate uniform 20x whole-slide view and uniform 1000x CY crop view'}],'references_not_converted_to_physical_specs':[{'reference':'25–50 um pipette opening','handling':'No source opening selected as calibrated tolerance. Fragile tip geometry illustrative and excluded from contact.'},{'reference':'Approximate 5 degree side-camera tilt','handling':'Reference metadata only; actual camera pose must be measured.'},{'reference':'12–20 um scans and 0.5–1 um z steps','handling':'No scan controller, imaging fidelity or resolved measurement implied.'},{'reference':'Triangular fiducial array','handling':'Synthetic example lattice only. Pitch/count/extent not inferred from source images.'}],'branch_local_holds':['220 versus 228 um maximum control-film thickness','Solid versus liquid surface tension in traction-window definition','Physical area versus polar-integral measure','CY9:10 measured versus inherited modulus','Normalized Piola–Kirchhoff stress versus other stress conventions','Ogden parameter sum and incompressibility terminology','Different dynamic-ridge speed descriptions','Humidity variation versus sensor accuracy','Macro 55 nL origin cannot apply automatically to 49 nL microscopy droplet','Equilibrium surface-tension inference is conditional, not a direct dynamic force measurement'],'source_figure_composition_copied':False,'source_raw_data_read_or_reanalyzed':False,'no_assertion_of_full_robot_implemented_paper':True})
