"""Write public scene metadata only. Does not import task evaluator data or sources."""
import json
from pathlib import Path
P=Path(__file__).resolve().parent
plan=json.loads((P/'task_binding_snapshot.json').read_text())
def put(n,x):(P/n).write_text(json.dumps(x,indent=2)+'\n')
meta={
 'schema':'laser_original_scene.v1','package_id':'laser_scene_assets_v1','version':'1.0.0','title':'Modulation-free laser control static laboratory','task_id':plan['task_id'],'task_family':'laser_control_operations_v2','source_doi':'10.1038/s41467-024-46319-3',
 'readiness':{'geometry':'Original generic sealed laboratory roles and original AFM carrier reuse','functionality':'Static scene plus caller-owned local metadata guards only','physical_execution':False,'device_io':False,'laser_energy_enabled':False,'heater1_enabled':False,'heater2_enabled':False,'servo_control':False,'optical_physics':False,'thermal_physics':False,'electronic_physics':False,'collision_validated':False,'physical_geometry_validated':False,'scientific_outputs':None,'whole_paper_complete':False},
 'files':{'editable':'geometry/laser_control_lab.blend','apparatus':'geometry/laser_control_lab.glb','display_only':'geometry/laser_pic_display.glb','generator':'geometry/build_scene.py'},
 'frame_convention':{'main_scene':'LASER_AUTHORED_METRIC','display_scene':'DISPLAY_ONLY_1000X','unit':'m','handedness':'right','up_axis_blender':'+Z','up_axis_gltf':'+Y','transform_direction':'local_to_parent','rotation_representation':'quaternion_xyzw','physical_qualified_transforms':None,'source_to_scene_axis_map':None,'note':'All source package poses and dimensions are unknown; bench XYZ placements are original presentation choices.'},
 'display_separation':{'display_only':True,'planar_footprint_scale_factor':1000,'native_footprint_m':[.00095,.00048],'native_area_m2':4.56e-7,'display_footprint_m':[.95,.48],'scale_applies_to':'Nominal 2D footprint reference only; not equipment, role legend, typography or any physical die','die_thickness_modelled':False,'source_circuit_layout_modelled':False,'native_reference_object':'pic.native_footprint_reference','display_reference_object':'display.pic_footprint_reference'},
 'source_known_facts':[
 {'fact':'PIC nominal footprint','value_m':[.00095,.00048],'area_m2':4.56e-7,'basis':'Final article implementation and source audit','implemented':'Exact flat XY extent reference only; no die thickness or source mask'},
 {'fact':'Final process label','value':'AIM Photonics 100 nm SOI','implemented':'Factual text; not a fabrication recipe or silicon thickness'},
 {'fact':'Silicon cross-section thickness','value_m':220e-9,'implemented':'Metadata and labelled text only; separate from process label'},
 {'fact':'Ring waveguide width','value_m':2.2e-6,'implemented':'Metadata only; no ring/waveguide CAD'},
 {'fact':'Approximate measured ring circumference','value_m':950e-6,'implemented':'Metadata only; does not instantiate SI ideal 1mm model'},
 {'fact':'Reported physical heater states','heater1':'off','heater2':'off','implemented':'Always disabled; no actuation interface'},
 {'fact':'Calibration route','value':'Open-loop tunable ECDL and calibrated 20 MHz fiber MZI','implemented':'Capped interface roles and empty record slots only'},
 {'fact':'Physical source routes','value':['DFB1','DFB2','DFB3'],'implemented':'Three distinct sealed modules, disabled'},
 {'fact':'Independent measurement','value':'Stabilized optical-frequency-comb-referenced heterodyne','implemented':'Closed capped reference chain; no signal or reference lock'},
 {'fact':'In-loop measurement','value':'FPGA relative laser-to-cavity error spectrum','implemented':'Separate role, explicitly not absolute frequency noise'},
 {'fact':'SiN example','value':'Numerical-only supplementary example','implemented':'Design-console text only; no second physical platform'}],
 'authored_geometry':{'known_source_cad':False,'source_geometry_traced':False,'all_equipment_dimensions':'unqualified authored metres','all_port_transforms':'unqualified authored poses','sealed_package':'original generic opaque housing; not vendor geometry','three_dfb_modules':'original generic housings; source identity roles only','fiber_and_cables':'original authored dormant capped presentation routes; no optical/electrical connectivity asserted','pcb':'closed external packaging service; no actual board, bond map or energized conductors','microring':'not modelled','footprint':'nominal flat reference only, no physical die','carrier_fit':'empty reused carrier and separate sealed package; no physical fit claim'},
 'source_boundaries':[
 {'id':'C01','issue':'Final comb-referenced heterodyne supersedes historical delayed self-heterodyne review route','handling':'Only final source route represented'},
 {'id':'C03','issue':'Final100nm process label, earlier180nm review label and220nm geometry are distinct','handling':'Final100nm label and220nm cross-section annotation; no process consistency claim'},
 {'id':'C04','issue':'Measured silicon ring and ideal SI1mm ring differ','handling':'No ring CAD or numerical solver'},
 {'id':'C05_C06','issue':'Gain normalization and optical power contexts differ','handling':'No gains, power settings or signal values produced'},
 {'id':'C07','issue':'SI SiN density value has unresolved plausibility/typography flag','handling':'Numerical model reproduction unavailable; no silent correction'},
 {'id':'C10','issue':'SiN example is numerical only','handling':'No physical SiN branch'}],
 'provenance':{'geometry':'Original authored scene and generic helper conventions adapted from prior original Apache-2.0 scene work. No source figures, circuit trace, CAD, code, screenshots or scientific result curves copied.','source_reference':{'title':'Modulation-free laser stabilization technique using integrated cavity-coupled Mach-Zehnder interferometer','url':'https://www.nature.com/articles/s41467-024-46319-3','doi':'10.1038/s41467-024-46319-3','license':'CC BY 4.0, subject to third-party exceptions','license_url':'https://creativecommons.org/licenses/by/4.0/','source_art_redistributed':False,'source_code_reused':False},'original_work_license':'Apache-2.0','reused_asset_families':['afm.sample_carrier','afm.retention_clamps'],'reused_mesh_count':15,'reused_new_unique_asset_credit':0,'reuse_fit_status':'Original mesh geometry and scale retained, empty carrier; no qualified laser-package fit','unique_asset_count':None,'counting_policy':'Ten semantic groups, three DFB instances, labels, repeated ports,15 reused meshes, two GLBs and three renders do not increase independent asset credit','fonts':'Built-in Blender Bfont; notice included'},
 'execution_gates':['Externally qualified foundry, packaging and alignment services','Verified actual laser safety/interlock and electrical qualification','Independent source identity, reference health, calibration and measurement evidence','No local state ever enables energy, hardware, servo control or scientific computation'],
 'publication_boundary':{'public_files':'EXPORT_ALLOWLIST.json only','remote_writes':'none by asset builder','excluded':'Source PDFs, images, extracted text, source code; evaluator data; logs, caches and backups'}}
put('asset_metadata.json',meta)
aff=json.loads((P/'affordances.json').read_text())['anchors'];by_name={a['scene_object']:a for a in aff}
ops=[];canonical=[]
for a in plan['scene_assets']:
 for aid in a['required_anchor_ids']:
  row=by_name[a['asset_id']+'.'+aid];canonical.append({k:row[k] for k in ['asset_id','anchor_id','scene_object','target_object']})
 for op in a['bind_operation_ids']:
  ops.append({'operation_id':op,'asset_id':a['asset_id'],'anchor_ids':a['required_anchor_ids'],'implementation':'visual_role_binding_only','physical_execution':False,'hardware_adapter':None,'scientific_adapter':None,'energy_enabled':False,'required_external_evidence':'task contract and qualified service, independently verified; scene state is not evidence'})
put('operation_bindings.json',{'schema':'laser_scene_bindings.v1','task_id':plan['task_id'],'binding_status':'STATIC_ROLE_BINDINGS_ONLY','operations':ops,'canonical_anchors':canonical,'task_execution_authority':False,'local_semantic_controls':'separate caller-owned demonstration metadata; do not execute task operations','integration_note':'Scene file availability does not upgrade operation executability or physical readiness'})
role_map={'A_DESIGN_CONSOLE':(['A17'],['E10','E11','E12']), 'A_FABRICATION_SERVICE':(['A03'],['E02']), 'A_PCB_SERVICE':(['A04','A11'],['E03']), 'A_PACKAGE_CUSTODY':(['A02'],['E01','E02']), 'A_SAFETY_ENCLOSURE':(['A01','A05','A06'],['E03','E04']), 'A_OPEN_LOOP_STATION':(['A07','A08','A09'],['E05']), 'A_DFB_CONTROL_STATION':(['A10','A12'],['E06']), 'A_REFERENCE_CHAIN':(['A14','A15'],['E07','E08']), 'A_FPGA_ANALYSIS':(['A13','A16'],['E06','E08','E09']), 'A_HOLD_PANEL':(['A18'],['E13'])}
put('review/source_comparison.json',{'schema':'laser_source_asset_comparison.v1','doi':meta['source_doi'],'inspected_figures':['Main Fig1','Main Fig2','Main Fig3','Main Fig4','Main Fig5','Main Fig6'],'source_artwork_used_in_exports':False,'source_pixels_used':False,'source_cad_used':False,'mode':'Original generic role abstraction; no circuit topology or exact apparatus reconstruction','ten_group_to_eighteen_source_role_map':[{'asset_id':k,'audit_role_ids':v[0],'source_evidence_ids':v[1]} for k,v in role_map.items()],'source_physical_routes':['DFB1','DFB2','DFB3'],'excluded_physical_routes':['SiN numerical example','historical delayed self-heterodyne'],'source_outcomes_drawn_or_emitted':False,'known_vs_authored_dimensions':meta['display_separation'],'verified_geometry_equivalence':False})
print('LASER_CONTRACTS_WRITTEN',len(ops),len(canonical))
