"""Build original Arc-Morph asset metadata from the locally accepted review.
This generator consumes only a portable requirements snapshot, not source CAD.
"""
import json
from pathlib import Path
P=Path(__file__).resolve().parent

def save(n,d):
 (P/n).write_text(json.dumps(d,indent=2)+'\n')
A=json.loads((P/'requirements_snapshot.json').read_text())['assets']
PRIMARY={0:'A01',1:'A01',2:'A02',3:'A03',4:'A04',5:'A04',6:'A04',7:'A06',8:'A12',9:'A07',10:'A07',11:'A08',12:'A10',13:'A07',14:'A07',15:'A10',16:'A08',17:'A09',18:'A01',19:'A07',20:'A11',21:'A11',22:'A11',23:'A12',24:'A12',25:'A01',26:'A11',27:'A11',28:'A05',29:'A12',30:'A07'}
OPS=[]
for i in range(31):
 op=f'R{i:02d}';assets=[x['id'] for x in A if op in x['operation_ids']]
 if PRIMARY[i] not in assets:assets.insert(0,PRIMARY[i])
 if i in [11,18]: assets=list(dict.fromkeys(assets+['A08','A09','A10']))
 if i in [19,30]:assets=list(dict.fromkeys(assets+['A11','A03']))
 OPS.append({'operation_id':op,'primary_asset_id':PRIMARY[i],'asset_ids':assets,'primary_anchor':f'ANCHOR.{op}.primary','control_anchor':f'ANCHOR.{op}.control','physical_execution_enabled':False,'qualified_pose':None,'fixture_binding':'Must resolve actual active fixture; generic anchor never authorizes cross-fixture release' if i in [19,30] else None})
save('operation_binding_contract.json',{'schema':'sciencegym.arcmorph.asset_binding.v1','units':'m','roots':{a['id']:'ASSET.'+a['id'] for a in A},'operation_ids':[f'R{i:02d}' for i in range(31)],'operations':OPS,'contract_status':'static nominal selectors only; physical qualification held'})
save('asset_metadata.json',{'schema':'sciencegym.original_scene_assets.v1','title':'Arc-Morph: original representative mechanics laboratory','asset_pack_id':'arcmorph_scene_assets_v1','task_id':'arcmorph_operations_v2','family_aliases':{'PP1':'PP'},'source':{'doi':'10.1038/s41467-025-57089-x','title':'Coarse-grained fundamental forms for characterizing isometries of trapezoid-based origami metamaterials','url':'https://www.nature.com/articles/s41467-025-57089-x','publication':'Nature Communications 16, 1823 (2025)','publisher_license':'CC BY-NC-ND 4.0; no paper images or CAD included','raw_archive_license_record':'CC BY 4.0; archive contents not inspected or reused'},'units':'m','native_editable':'geometry/arcmorph_lab.blend','portable':['geometry/arcmorph_lab.glb'],'evidence':['evidence/overview.png','evidence/handling.png','evidence/metrology.png'],'original_geometry_license':'Apache-2.0','groups':12,'physical_families':['CS1','CS2','CS3','CS4','PP1'],'physical_geometry_validated':False,'physical_execution_enabled':False,'scientific_success':False,'source_pixels_or_CAD_used':False,'raw_archive_or_code_read':False,'not_implemented':['robot motion','rigid or deformable physics','qualified fabrication','physical folding','load safety','real device controls','real optical calibration','raw-data acquisition or source reanalysis','mathematical oracle','whole-paper scientific reproduction'],'source_known_dimensions':{'PP_width_mm':428.78,'PP_nominal_thickness_mm':1,'bolt_diameter_mm':2,'PP_length_methods_mm':383.63,'PP_length_figure_mm':383.65},'dimensional_hold':{'conflict_id':'C01','resolution':None,'fabrication_from_source_dimensions_allowed':False,'message':'383.63 mm Methods versus 383.65 mm Fig.4A; no preferred value selected'},'authored_template_generation_parameters_mm':{'CS1':[300,200,0.35],'CS2':[320,200,0.35],'CS3':[300,220,0.35],'CS4':[320,220,0.35],'PP1':[420,360,1]},'dimension_semantics':'Family W/D/T values are nominal generator inputs; warped representative surface extents are separately measured in specimen_topology.json and are not fabrication dimensions.','template_status':'Original illustrative vertex embeddings and candidate crease graphs. Not source geometry, validated rigid folding, or physically qualified sheets. All equipment envelopes, layouts, grips, mounts and motion interfaces are authored nominal placeholders unless explicitly source-known.'})
save('variants.json',{'schema':'sciencegym.arcmorph.variants.v1','variants':[{'family_id':f,'source_family_role':role,'default_visual_state':'illustrative_folded','available_static_geometry_states':['flat','part_folded','illustrative_folded','damaged'],'qualified_state_available':False,'state_change_is_physical_folding':False,'geometry_basis':'Original representative panel/crease embedding; no source pattern reconstruction','dimensions_mm':json.loads((P/'asset_metadata.json').read_text())['authored_template_generation_parameters_mm'][f],'source_family_identity_only':True} for f,role in [('CS1','Arc-Miura cardstock'),('CS2','Extended Arc-Miura cardstock'),('CS3','Archimedean spiral cardstock'),('CS4','Lemniscate of Bernoulli cardstock'),('PP1','polypropylene rigid / qualitative specimen')]],'identity_caution':'Five asset design exemplars are not five experimental samples; alternate static geometry states are not captures or new specimens.'})
