"""Reconstruct descriptive contracts from retained authored facts and stable interface.
No source files or private paths are inputs; never derive physical qualification.
"""
import json
from pathlib import Path
P=Path(__file__).resolve().parent
def put(n,j):(P/n).write_text(json.dumps(j,indent=2)+'\n')
plan=json.loads((P/'task_binding_snapshot.json').read_text())
put('operation_bindings.json',{'task_id':plan['task_id'],'implementation':'static_scene_and_local_metadata_only','operations':[{'operation_id':op,'asset_id':a['asset_id'],'anchor_ids':a['required_anchor_ids'],'physical_execution':False,'energy_enabled':False,'hardware_adapter':None,'coordinate_status':'authored_unqualified'} for a in plan['scene_assets'] for op in a['bind_operation_ids']],'canonical_anchors':[{'asset_id':a['asset_id'],'anchor_id':key,'scene_object':a['asset_id']+'.'+key} for a in plan['scene_assets'] for key in a['required_anchor_ids']]})
put('asset_metadata.json',{
 'schema':'woven_original_scene.v1','package_id':'woven_scene_assets_v1','version':'1.0.0','title':'Woven-material static research laboratory','task_id':plan['task_id'],'task_family':'woven_material_operations_v2','source_doi':'10.1038/s41467-026-68298-3',
 'recovery':{'status':'reconstructed_and_regenerated_new_artifact','basis':'Retained exact original author tool-call content and independently recovered stable task interface','prior_binary_identity_claimed':False,'prior_review_applied_to_new_files':False},
 'readiness':{'geometry':'Original generic laboratory and deliberately incomplete illustrative beam roles','functionality':'Static scene plus caller-owned symbolic record guards only','physical_execution':False,'device_io':False,'energy_enabled':False,'fabrication_enabled':False,'chemistry_enabled':False,'cpd_enabled':False,'plasma_enabled':False,'coating_enabled':False,'loading_enabled':False,'sem_enabled':False,'physics':False,'collision_validated':False,'physical_geometry_validated':False,'scientific_outputs':None,'whole_paper_complete':False},
 'files':{'editable':'geometry/woven_material_lab.blend','apparatus':'geometry/woven_material_lab.glb','display_only':'geometry/woven_reference_display.glb','generator':'geometry/build_scene.py'},
 'frame_convention':{'main_scene':'WOVEN_AUTHORED_METRIC','display_scene':'DISPLAY_ONLY_1000X','unit':'m','handedness':'right','up_axis_blender':'+Z','up_axis_gltf':'+Y','transform_direction':'local_to_parent','rotation_representation':'quaternion_xyzw','physical_qualified_transforms':None,'source_to_scene_axis_map':None,'note':'All apparatus poses and dimensions are original unqualified presentation choices; cell and fiber radius references alone use known source dimensions.'},
 'display_separation':{'display_only':True,'reference_scale_factor':1000,'native_cell_m':60e-6,'display_cell_m':.06,'native_fiber_radius_m':1e-6,'display_fiber_radius_m':.001,'scale_applies_to':'Cell dimension and separate fiber-radius references only, not bench, apparatus, labels, plinth, node connections or physical fixtures','native_reference_object':'native.cell_reference','display_reference_objects':['display.BCC.cell_reference','display.CUBIC.cell_reference'],'generic_beam_roles':'Three/four strands per BCC-like/cubic-like beam respectively; authored one-turn phase, 3 mm display offset, 10% open node gaps; no paper-exact topology or continuity claim','tetrakaidecahedron_modelled':False},
 'source_known_facts':[
 {'fact':'Core source unit-cell size','value_m':60e-6,'implemented':'Native reference cube and separate exact 1000x edge references only'},
 {'fact':'Fiber radius','value_m':1e-6,'implemented':'Native radius cylinder and separate exact 1000x cylinder'},
 {'fact':'Tetrakaidecahedron cell size','value_m':120e-6,'implemented':'Metadata only; strand-count conflict held, no geometry'},
 {'fact':'Effective-radius experimental range','value_m':[2e-6,6e-6],'implemented':'Metadata only; illustrative helix offset is independently authored'},
 {'fact':'BCC beam strand role','value':3,'implemented':'Generic open-ended illustrative bundles only'},
 {'fact':'Cubic beam strand role','value':4,'implemented':'Generic open-ended illustrative bundles only'},
 {'fact':'Nominal gold coat','value_m':10e-9,'implemented':'Factual service label only; no layer, recipe, thickness verification or sputter control'},
 {'fact':'Physical tension arrangement','value':'Microgripper engages monolithic top fixture; lattice base remains attached to silicon substrate','implemented':'Generic unqualified upper-fixture and lower silicon-support roles; no contact with native fibers or physical sample geometry'},
 {'fact':'Paired acquisition','value':'Load-displacement plus SEM imaging','implemented':'Separate empty external record slots; no acquisition or result'},
 {'fact':'Optional patterned scaffold removal','value':'External plasma service after development and CPD','implemented':'Sealed branch-specific receipt dock; no source pattern copied, no plasma actuation'}],
 'authored_geometry':{'known_source_cad':False,'source_geometry_traced':False,'all_equipment_dimensions':'unqualified authored metres','all_anchor_transforms':'unqualified authored poses','carrier_fit':'fresh generic closed carrier; no fit, grasp, clearance or transport qualification','tension_fixture':'generic external support and top-fixture roles; no replica and no actual lattice','woven_display':'original mathematical beam illustrations with intentionally omitted nodes and strand connections','scientific_response_modelled':False},
 'source_boundaries':[{'id':'C_TETRA_STRANDS','handling':'No tetrakaidecahedron geometry or selectable local metadata'},{'id':'C_MODULAR_RULE','handling':'No source algorithm implementation; generic open node gaps and no continuity qualification'},{'id':'C_SCHEME_POWER','handling':'No plasma-versus-coating order drawn or enforced; receipt bundle alone does not prove chronology'},{'id':'C_PATTERN_AXES','handling':'No patterned specimen, axis map or source letters'},{'id':'C_FAILURE_DEFINITION','handling':'No threshold or failure physics'},{'id':'C_WORK_DISSIPATION','handling':'No energy result or integration'},{'id':'C_PATTERN_PARAMETER_MAP','handling':'Physical high-turn and simulated parameter maps remain distinct and held; no source pattern geometry or metrics'}],
 'provenance':{'geometry':'Original authored scene; generic helper conventions adapted from earlier original Apache-2.0 scene work. Reconstructed from retained original author commands. No source figures, source meshes, CAD, source code, result curves or source pixels copied.','source_reference':{'title':'Design framework for programmable three-dimensional woven metamaterials','url':'https://www.nature.com/articles/s41467-026-68298-3','doi':'10.1038/s41467-026-68298-3','license':'CC BY-NC-ND 4.0, subject to third-party exceptions','license_url':'https://creativecommons.org/licenses/by-nc-nd/4.0/','source_art_redistributed':False,'source_code_reused':False},'original_work_license':'Apache-2.0','reused_asset_families':[],'reused_mesh_count':0,'reused_new_unique_asset_credit':0,'unique_asset_count':None,'counting_policy':'Eleven semantic role groups, repeated meshes, labels, two GLBs and three renders do not establish independent unique-asset credit. No prior AFM mesh reused.','fonts':'Built-in Blender Bfont; notice included'},
 'execution_gates':['Actual apparatus, geometry, custody, chronology, qualification and calibration require independent external evidence','Local claims and imported record identifiers are untrusted labels','No local metadata can enable any physical service or scientific computation'],
 'publication_boundary':{'public_files':'EXPORT_ALLOWLIST.json only','remote_writes':'none by asset builder','excluded':'Source papers, figures, text, code, movies, datasets; evaluator data; logs, caches and backups'}})
put('states.json',{'scope':'caller_owned_untrusted_symbolic_metadata','states':['CUSTODY','DOCKED','SERVICES_BOUND','FIXTURE_DISABLED','RECORDS_BOUND','DISCONNECTED','QUARANTINE'],'default':'CUSTODY','all_physical_services':'PERMANENTLY_DISABLED','quarantine':'terminal local hold; not physical shutdown','retrieval':'clears downstream active metadata; previous acquisition IDs cannot be reused','display_geometry_coupled':False,'claims_are_evidence':False,'plasma_gold_order':'unspecified; no locally synthesized chronology','scientific_outputs':None})
roles=[('woven_design_console','A_DESIGN_CONSOLE','generic_role'),('silicon_carrier','A_MICROCARRIER','generic_closed_proxy'),('bcc_woven_specimen','DISPLAY.woven_reference','open_node_schematic_only'),('cubic_woven_specimen','DISPLAY.woven_reference','open_node_schematic_only'),('tensile_fixture_base','A_TENSION_FIXTURE','generic_support_role'),('two_photon_station','A_FABRICATION_SERVICE','closed_receipt_only'),('resin_container','A_FABRICATION_SERVICE','receipt_role_no_container_geometry'),('development_station','A_FABRICATION_SERVICE','closed_receipt_only'),('rinse_station','A_FABRICATION_SERVICE','closed_receipt_only'),('critical_point_dryer','A_CPD_SERVICE','closed_receipt_only'),('gold_sputter_station','A_COATING_SERVICE','closed_receipt_only'),('sem_nanoindenter_station','A_SEM_HOLDER','closed_holder_and_external_records'),('microgripper','A_TENSION_FIXTURE','generic_top_fixture_contact_role'),('analysis_console','A_ANALYSIS_CONSOLE','empty_record_console'),('calibration_reference','A_ACQUISITION_RECORDS','empty_external_record_slot'),('patterned_support_proxy','A_PLASMA_SERVICE','branch_held_no_pattern_geometry'),('oxygen_plasma_station','A_PLASMA_SERVICE','closed_receipt_only')]
put('review/source_comparison.json',{'source_doi':'10.1038/s41467-026-68298-3','reference_basis':'Retained factual audit and original source inspection recorded before workspace loss; no new raw-source reconstruction','references_inspected_before_recovery':['Main Methods geometric parameters and fabrication/characterization','Supplementary Fig S10 page 13: top fixture and silicon base roles','Supplementary Note S1 page 1: no copying of source node-generation geometry'],'source_art_redistributed':False,'source_pixels_used':False,'source_code_reused':False,'source_meshes_reused':False,'source_outcomes_drawn_or_emitted':False,'source_role_map':[{'asset_id':a['asset_id'],'source_role':a['role'],'deviation':a.get('source_facts_and_limits','Original unqualified geometry')} for a in plan['scene_assets']],'source_role_coverage':[{'audit_role':k,'scene_group':v,'status':s} for k,v,s in roles],'geometry_limit':'Only cell extent and fiber radius reference primitives instantiate exact microdimensions. Display strands deliberately do not reproduce continuous source nodes. Source tension roles are represented generically with no native fiber contact.','license_boundary':'CC BY-NC-ND source used for reference facts; no adapted or copied source art or geometry exported.'})
(P/'LICENSES/ATTRIBUTION.md').write_text('''# Original work and reference boundary

Original scene, metadata and local guard code: Apache-2.0. Generic helper conventions draw on prior original scene work; no prior specimen or apparatus meshes are reused. This version was reconstructed from retained original author commands and regenerated as a new artifact.

Reference: Molly Carton, James Utama Surjadi, Bastien F. G. Aymon, Ling Xu and Carlos M. Portela, “Design framework for programmable three-dimensional woven metamaterials,” Nature Communications, DOI 10.1038/s41467-026-68298-3. https://www.nature.com/articles/s41467-026-68298-3

The article is CC BY-NC-ND 4.0 subject to third-party exceptions. https://creativecommons.org/licenses/by-nc-nd/4.0/
No source art, figures, source CAD, source code, source mesh, movies, data or adaptations of them are distributed. Facts and generic apparatus roles informed this independently authored scene. The generic woven illustration is not a source-exact reconstruction and has open nodes. The tetrakaidecahedron branch is held, not reconstructed.

Built-in Blender Bfont notice is included.
''')
(P/'review/SOURCE_TO_ASSET_AUDIT.md').write_text('''# Source-to-asset audit

The original scene separates the sealed carrier, generic tension support, closed SEM holder, fabrication/development dock, CPD dock, gold-coating dock and optional plasma-support-removal dock. Main Methods and SI S10 inform semantic roles only. The top fixture is gripped; the lower role represents a silicon substrate support, not a native fiber grasp. All geometry and transforms are unqualified.

A native 60 µm cube and 1 µm-radius cylinder are dimensional references only. A second scene magnifies these dimensions by exactly 1000. Open-ended BCC-like and cubic-like bundles communicate three/four-strand beam roles without implementing source nodes, connectivity, the conflicted modular rule, or source code. Their phase, gaps and presentation are independently authored. Tetrakaidecahedron geometry is absent.

Development and CPD precede optional plasma in the source; gold precedes SEM. Plasma-versus-gold ordering is unspecified. The scene offers separate receipt docks and a shared sample ID without a fixed process-order route. A local receipt bundle does not prove actual sequence. Source patterned letters, source figures and scientific outputs are absent.

No appearance, record token, guard, static pose or file validates material properties, physical qualification, collision safety, calibration, chronology, SEM operation or source reproduction. Recovery uses retained original author content; no raw source files or source geometry were recreated, and all generated bytes require fresh verification.
''')
print('CONTRACTS_WRITTEN')
