import json,tempfile,unittest,hashlib
from pathlib import Path
from verify_export import verify
class ExportTests(unittest.TestCase):
 def setUp(self):
  self.tmp=tempfile.TemporaryDirectory();self.root=Path(self.tmp.name)
  for n,s in [('agent_visible.json','{}'),('README.md','Original synthetic export fixture')]: (self.root/n).write_text(s)
  self.a={'files':['EXPORT_ALLOWLIST.json','README.md','agent_visible.json'],'payload_sha256':{n:hashlib.sha256((self.root/n).read_bytes()).hexdigest() for n in ['README.md','agent_visible.json']},'publisher_files_included':False,'actor_file_allowlist':['agent_visible.json'],'publication_authority':'parent_only'};self.write()
 def tearDown(self):self.tmp.cleanup()
 def write(self):(self.root/'EXPORT_ALLOWLIST.json').write_text(json.dumps(self.a))
 def rejected(self):self.assertTrue(verify(self.root))
 def test_valid_fixture(self):self.assertEqual(verify(self.root),[])
 def test_unlisted(self):(self.root/'unlisted.md').write_text('extra');self.rejected()
 def test_missing(self):(self.root/'README.md').unlink();self.rejected()
 def test_changed(self):(self.root/'README.md').write_text('changed');self.rejected()
 def test_source_binary(self):(self.root/'source.pdf').write_bytes(b'%PDF');self.rejected()
 def test_symlink(self):(self.root/'link.md').symlink_to(self.root/'README.md');self.rejected()
 def test_dangling_link(self):(self.root/'bad.md').symlink_to(self.root/'absent');self.rejected()
 def test_directory_link(self):(self.root/'directory').symlink_to(self.root,target_is_directory=True);self.rejected()
 def test_traversal(self):self.a['files'].append('../bad.md');self.write();self.rejected()
 def test_absolute(self):self.a['files'].append('/bad.md');self.write();self.rejected()
 def test_backslash(self):self.a['files'].append('a\\b.md');self.write();self.rejected()
 def test_uri(self):self.a['files'].append('file:bad.md');self.write();self.rejected()
 def test_duplicate(self):self.a['files'].append('README.md');self.write();self.rejected()
 def test_empty(self):self.a['files']=[];self.write();self.rejected()
 def test_missing_hash(self):self.a['payload_sha256'].pop('README.md');self.write();self.rejected()
 def test_unknown_hash(self):self.a['payload_sha256']['bad.md']='0'*64;self.write();self.rejected()
 def test_invalid_hash(self):self.a['payload_sha256']['README.md']='bad';self.write();self.rejected()
 def test_actor_scope(self):self.a['actor_file_allowlist'].append('source_outcomes.json');self.write();self.rejected()
 def test_publisher_scope(self):self.a['publisher_files_included']=True;self.write();self.rejected()
 def test_publication_scope(self):self.a['publication_authority']='author';self.write();self.rejected()
 def test_duplicate_json_key(self):(self.root/'EXPORT_ALLOWLIST.json').write_text('{"files":[],"files":[]}');self.rejected()
 def test_missing_allowlist(self):(self.root/'EXPORT_ALLOWLIST.json').unlink();self.rejected()
 def test_malformed(self):(self.root/'EXPORT_ALLOWLIST.json').write_text('{');self.rejected()
 def test_nonstring_name(self):self.a['files'].append(3);self.write();self.rejected()
if __name__=='__main__':unittest.main()
