"""Structural design checks only; no hardware qualification or scientific reproduction."""
from pathlib import Path
import json,sys
ROOT=Path(__file__).resolve().parents[1]
def read(n):return json.loads((ROOT/n).read_text())
def verify(root=ROOT):
 root=Path(root);checks=[]
 def load(n):return json.loads((root/n).read_text())
 def ck(name,test):
  if not test:raise ValueError(name)
  checks.append(name)
 op_rows=load('operations.json')['operations'];ops={x['id']:x for x in op_rows};b=load('branches.json');routes={x['id']:x for x in b['physical_routes']};aux={x['id'] for x in b['auxiliary_routes']};theory={x['id'] for x in b['nonmanual_dispositions']};assets=load('asset_binding_plan.json');facts=load('source_parameters.json')['facts'];conf=load('source_conflicts.json')['conflicts'];unknown=load('unknown_parameters.json')['unknowns'];coverage=load('coverage_matrix.json')['coverage']
 ck('31 exact unique operation templates',len(op_rows)==len(ops)==31 and set(ops)=={f'R{i:02}' for i in range(31)})
 ck('seven physical route families',set(routes)=={'CS1','CS2','CS3','CS4','PP_PREP','PP_RIGID','PP_SHEAR'})
 ck('two auxiliary dispositions',aux=={'PHOTO_ANALYSIS','CLOSEOUT'})
 ck('six nonmanual dispositions',theory=={f'N{i:02}' for i in range(1,7)})
 ck('ten source facts',len(facts)==10 and {x['id'] for x in facts}=={f'F{i:02}' for i in range(1,11)})
 ck('ten conflict cards',len(conf)==10 and {x['id'] for x in conf}=={f'C{i:02}' for i in range(1,11)})
 ck('fourteen unknown cards',len(unknown)==14 and {x['id'] for x in unknown}=={f'U{i:02}' for i in range(1,15)})
 ck('twenty coverage records',len(coverage)==20 and {x['id'] for x in coverage}=={f'CV{i:02}' for i in range(1,21)})
 ck('all route dispositions covered',set().union(*(set(x['route_ids']) for x in coverage))==set(routes)|aux|theory)
 ck('twelve original asset groups',len(assets['assets'])==12 and {x['id'] for x in assets['assets']}=={f'A{i:02}' for i in range(1,13)})
 ck('every operation has one semantic binding',len(assets['operation_bindings'])==31 and {x['operation_id'] for x in assets['operation_bindings']}==set(ops))
 for bind in assets['operation_bindings']:
  o=ops[bind['operation_id']];ck('operation binding '+o['id'],o['asset_ids']==bind['asset_ids'] and o['anchor_ids']==bind['anchor_ids'] and bind['anchor_ids']==['ANCHOR.'+o['id']+'.primary','ANCHOR.'+o['id']+'.control'] and bind['root_node_ids']==['ASSET.'+x for x in bind['asset_ids']] and bind['physical_qualified'] is False and all(type(bind[k]) is str and bind[k] and o[k]==bind[k] for k in ('primary_asset_id','primary_target','control_target')))
 ck('all operations authored',all(x['provenance_class']=='authored_robot_translation' and x['source_is_robot_protocol'] is False and x['physical_implemented'] is False for x in ops.values()))
 ck('no actor observation authority',all(x['actor_event_fields']==['event_id','operation_id','evidence_id'] for x in ops.values()))
 ck('service binding not completion',ops['R04']['evidence_role']=='request_binding' and ops['R05']['evidence_role']=='independent_scoped_record')
 ck('source references valid',all(set(x['source_fact_ids'])<={f'F{i:02}' for i in range(1,11)} for x in ops.values()))
 ck('conflict backlinks exact',all(set(x['conflict_ids'])=={c['id'] for c in conf if x['id'] in c['operation_ids']} for x in ops.values()))
 ck('unknown backlinks exact',all(set(x['unknown_ids'])=={u['id'] for u in unknown if x['id'] in u['operation_ids']} for x in ops.values()))
 ck('unknown numeric defaults absent',all(x['default'] is None and x['physical_default'] is None for x in unknown))
 ck('cardstock each has three slots',all(routes[f'CS{i}']['state_slots']==['ground','rigid','sheared'] for i in range(1,5)))
 ck('cardstock each has full preparation and release paths',all({'prepare','baseline','rigid_demo','shear_demo','closeout'}==set(routes[f'CS{i}']['operation_groups']) and 'R07' in routes[f'CS{i}']['operation_groups']['prepare'] and 'R30' in routes[f'CS{i}']['operation_groups']['rigid_demo'] and 'R22' in routes[f'CS{i}']['operation_groups']['shear_demo'] for i in range(1,5)))
 pp=routes['PP_RIGID'];ck('eight canonical height slots',len(pp['state_loop']['instances'])==8 and [x['id'] for x in pp['state_loop']['instances']]==[f'H{i:02}' for i in range(1,9)] and pp['state_loop']['same_specimen_required'] is True)
 ck('rigid loop locks captures pair release',pp['state_loop']['per_instance']==['R13','R14','R15','R16','R17','R18','R19'])
 ck('PP branches depend on preparation',all('PP_PREP' in routes[x]['dependencies'] for x in ['PP_RIGID','PP_SHEAR']))
 ck('folding explicit before baseline',routes['PP_PREP']['operation_sequence'].index('R07')<routes['PP_PREP']['operation_sequence'].index('R08'))
 ck('rigid unmount before transfer',pp['closeout'][:2]==['R30','R03'])
 sh=routes['PP_SHEAR']['operation_sequence'];ck('corner unmount before return',sh.index('R19')<sh.index('R22')<len(sh)-1 and sh[sh.index('R22')+1]=='R03')
 controls=load('controls_and_repeats.json');ck('one source specimen and set',controls['source_quantitative_specimens']==controls['source_quantitative_sets']==1 and controls['source_configurations']==8 and controls['source_technical_repeats_per_configuration'] is None)
 ck('six separate controls',len(controls['controls'])==6)
 out=load('source_outcomes.json');ck('outcomes reviewer only',out['visibility']=='reviewer_and_future_evaluator_only' and len(out['rows'])==8 and out['data_class']=='published_observations_not_benchmark_targets')
 ck('radii stay separately named',all({'height','exterior_radius','interior_radius'}<=set(x) for x in out['rows']))
 ck('actor only allowed file',load('evaluator_reference.json')['actor_visible_allowlist']==['agent_visible.json'] and load('evaluator_reference.json')['isolation_implemented'] is False)
 ck('actor no source output authority',load('agent_visible.json')['source_outcomes_exposed'] is False and load('agent_visible.json')['can_declare_observation'] is False)
 ck('all physical branches reach failure accounting',{x['route_id'] for x in load('lifecycle_contract.json')['failure_edges']}==set(routes))
 transfers=load('transport_routes.json')['transfers'];ck('35 explicit transfer templates',len(transfers)==35 and len({x['id'] for x in transfers})==35)
 ck('transport guards explicit',all(x['carrier_required'] is True and x['unmounted_and_unloaded_required'] is True for x in transfers))
 ck('five material family identities',{x['family_id'] for x in load('material_cards.json')['cards']}=={'CS1','CS2','CS3','CS4','PP'})
 ck('scene polymer alias explicit',assets['family_aliases']=={'PP1':'PP'})
 ck('model separate from measured radii',load('analysis_contracts.json')['distinct_model_field']=='coarse_grained_radius_prediction')
 ck('all six main figures accounted',load('coverage_matrix.json')['all_main_figures_dispositioned']==list(range(1,7)))
 ck('all eight SI figures accounted',load('coverage_matrix.json')['all_SI_figures_dispositioned']==list(range(1,9)))
 audit=load('source_access_audit.json');src={x['id']:x for x in audit['sources']};ck('main twelve pages read',src['MAIN']['all_text_pages_read']==list(range(1,13)));ck('SI twenty-two pages read',src['SI']['all_text_pages_read']==list(range(1,23)))
 ck('raw archive not acquired','archive bytes not acquired' in src['DATA']['status'])
 boundary=load('RELEASE_BOUNDARY.json');ck('zero physical execution and reproduction',boundary['validated_runnable_whole_paper_tasks']==0 and all(boundary[x] is False for x in ['whole_paper_execution_complete','physical_execution','physical_simulation','scientific_reproduction','source_data_reanalysis','source_files_exported','exact_geometry_validated','hardware_safety_qualified','source_math_validated','repository_changes','remote_writes']))
 ck('scoped source model conflicts preserved',all(c['status']=='open' for c in conf) and len([c for c in conf if c['id'] in ['C08','C09','C10']])==3)
 ck('no silently averaged length',facts[1]['reported']['height_mm_methods']==383.63 and facts[1]['reported']['height_mm_figure']==383.65)
 ck('source theory not physical drawing',facts[7]['reported']['not_physical_specimen_defaults'] is True)
 return {'passed':True,'check_count':len(checks),'checks':checks,'physical_execution':False,'scientific_reproduction':False}
if __name__=='__main__':
 try:print(json.dumps(verify(),indent=2))
 except (ValueError,KeyError) as e:print(str(e));sys.exit(1)
