"""Bounded PAIRED_TWO visual episode specification; no process or data backend."""
from pathlib import Path
import os,json,hashlib
def external_root(variable):
 value=os.environ.get(variable)
 if not value:
  raise SystemExit('Set '+variable+' to the existing external input directory. See EXTERNAL_INPUTS.md.')
 root=Path(value).expanduser().resolve()
 if not root.is_dir():
  raise SystemExit(variable+' must identify an existing directory. See EXTERNAL_INPUTS.md.')
 return root

OUT=Path(__file__).resolve().parents[1]
TASK=external_root('THERMO_TASKS')
URL='https://github.com/openags/ScienceGym/blob/2f926a9d2c2b8a0c71e8939feaa6ca5696e14c27/tasks/thermoelectric_operations_v2/'
branch=next(b for b in json.loads((TASK/'branches.json').read_text())['branches'] if b['id']=='PAIRED_TWO')
ops={o['id']:o for o in json.loads((TASK/'operations.json').read_text())['operations']}
frames=[]
def add(fid,title,st,kind,material,ids,before,after,obj,note='',**kw):
 n=len(frames)+1
 frames.append(dict(id=fid,index=n,title=title,image=f'frames/{n:02d}_{fid}.jpg',action=' '.join(a for i in ids for a in ops[i]['actions']) if ids else 'Inspect the authored episode state; no operation is executed.',station=st,objects=obj,sample_state_before=before,sample_state_after=after,evidence={'branch':'PAIRED_TWO','operation_ids':ids,'source_refs':sorted(set(e for i in ids for e in ops[i]['evidence_ids'])),'operation_file':URL+'operations.json','branch_file':URL+'branches.json','source_scene':'thermoelectric_scene_v3'},authored_notes='Static/kinematic visual keyframe, not robot execution. '+note,phase=material,visual_kind=kind,rendered=False,physical_object_id='module.PAIRED_TWO.001' if material=='PAIR' else None,**kw))
add('START','Raw materials only; the laboratory is idle','WS_STOCK','initial','P',[], 'Sealed raw stock; empty downstream sample locations','One intended P/N route selected; no finished sample','Raw Mg, Ag, Sb, C18H36O2, In, Bi, Te; empty containers','All original downstream temporal sample copies are hidden; unrelated B/segmented/contact stations stay inactive.')
for c in ['P','N']:
 ident='MgAgSb + 0.625 wt% C18H36O2' if c=='P' else 'Mg3.2In0.02Sb0.595Bi1.4Te0.005'
 width='3.3' if c=='P' else '2.9'; stack='Sb / P / Sb' if c=='P' else 'stainless steel / N / stainless steel';sps='SPS-322LX' if c=='P' else 'SPS-1080'
 pfx=c+' · '
 add(c+'_PORTION',pfx+'retrieve and portion separately','WS_PREP','portion',c,['STOCK','PREP_NEST','PORTION'],c+' raw constituents sealed; empty labelled jar',c+' symbolic portion staged; original identity retained',c+' raw-source carrier + '+c+' jar', 'Three setup operations aggregated. Real masses, yield and portion recipe are not supplied. '+ident)
 add(c+'_CAP',pfx+'close the labelled jar','WS_PREP','cap',c,['VIAL_CLOSE'],c+' portion in jar; cap separate',c+' jar closed on numbered carrier',c+' jar and cap','Cap geometry and closure pose are authored; seal not validated.')
 add(c+'_AR',pfx+'closed Ar handoff and return','WS_ATMOSPHERE','ar',c,['AR_HANDOFF','AR_RETURN'],c+' closed jar; atmosphere not established',c+' jar returned after a storyboard gate',c+' closed jar / authored handoff drawer','Two handoff operations aggregated. No gas model or atmosphere certificate was executed; Ar remains an intended equipment event.')
 add(c+'_MILL_SEAT',pfx+'stage the jar at the mill handoff cradle','WS_MILL','mill_seat',c,['MILL_OPEN','MILL_SEAT','MILL_CLAMP'],c+' jar in supported transfer tray',c+' jar in separate authored task cradle',c+' jar / authored cradle','Three operations aggregated. Existing SPEX approximately 7 mm vial/clamp gap retained; authored cradle does not validate actual clamping or fit.')
 add(c+'_MILL_RUN',pfx+'withdraw and select the mill job','WS_MILL','mill_run',c,['MILL_CLOSE','MILL_RUN'],c+' jar staged; hands at loading target',c+' work order illustrated; robot withdrawn',c+' job card; no active motion','Cover closure and start aggregated. No milling, vibration, power or powder generation; processing interval omitted.')
 add(c+'_MILL_UNLOAD',pfx+'support and retrieve the same jar','WS_MILL','mill_unload',c,['MILL_UNLOAD'],c+' job terminal/safe-release event is a storyboard assumption',c+' closed jar back on supported carrier',c+' jar, same parent ID','No verified safe-release backend; this is the intended unloading keyframe.')
 add(c+'_STACK',pfx+'sealed powder to separate die stack','WS_DIE','stack',c,['POWDER_DECANT','DIE_ASSEMBLE',c+'_STACK','DIE_CLOSE'],c+' jar from mill; dedicated die empty',stack+' stack sealed in die proxy',c+' powder capsule + interface cartridge + die','Four actions and powder-to-die transport aggregated. Layer masses/thickness, leveling, die geometry and atmosphere interfaces are unknown; powder is an inert closed prop.')
 add(c+'_SPS_LOAD',pfx+'load the '+sps+' role','WS_SPS','sps_load',c,['SPS_LOAD'],c+' labelled die carrier closed',c+' die carrier in its separate service drawer',c+' die carrier / '+sps,'Housing, drawer and handoff are authored proxies; material-specific work order stays distinct.')
 add(c+'_SPS_RELEASE',pfx+'job gate and cold-state release','WS_SPS','sps_release',c,['SPS_RUN','SPS_UNLOAD'],c+' die seated; robot withdrawn',c+' die retrieved after illustrated cooling gate',c+' die carrier / '+sps,'Process interval and cooling gate are symbolic. No pressure, temperature, sintering or trusted safe-release event executed.')
 add(c+'_DEMOLD',pfx+'demold and preserve the parent axis','WS_DIE','demold',c,['DEMOLD'],c+' released die and parent record',c+' billet proxy carries its original parent',c+' billet + pressing-axis marker','Billet dimensions and tooling are authored, not recovered specimen measurements.')
 add(c+'_CUT',pfx+'register dimensions and cut direction','WS_CUT','cut',c,['CUT_FIXTURE','CUT_SELECT','CUT_RUN'],c+' billet supported in direction fixture',c+' enclosed cutting job illustrated',c+' billet / dimension card','Three cutting setup/run operations aggregated; no cutting executed. '+('P cutting parallel to the pressing axis is source-supported.' if c=='P' else 'N cutting direction is explicitly unknown; it does not inherit P direction.'))
 add(c+'_LEGS',pfx+'retrieve two distinct '+width+' mm legs','WS_CUT','legs',c,['CUT_UNLOAD'],c+' billet parent; cutting completion is symbolic',c+'1 and '+c+'2 in independent tray compartments',c+'1, '+c+'2; '+width+' x '+width+' x 6.6 mm each','Four source leg envelopes remain distinct by material; drawn at 20x linear scale. Kerf/yield/tolerances and interface-thickness convention unknown.')
add('MODULE_BASE','Place the AlN support and lower copper','WS_MODULE','module_base','PAIR',['MODULE_BASE'],'P1/P2 and N1/N2 in labelled compartments; no module','AlN support and lower electrodes in authored jig','AlN support + lower Cu','AlN dimensions, electrode routing and joining details are authored or unknown, not recovered measurements.')
for i,c in enumerate(['P1','N1','P2','N2']):
 add('PLACE_'+c,'Place '+c+' while retaining all four identities','WS_MODULE','module_leg','PAIR',['MODULE_LEGS'],f'{i} of 4 legs placed; remaining legs in carrier',f'{i+1} of 4 legs placed; '+c+' parent recorded',c+' / four-leg assembly','MODULE_LEGS is expanded into four individual placement keyframes. The displayed 20x scale supports inspection; grasp pose is illustrative.',leg_index=i)
add('MODULE_BRIDGE','Align copper bridges; preserve polarity labels','WS_MODULE','module_bridge','PAIR',['MODULE_BRIDGE'],'Four identified legs seated; top bridges separate','Two-pair topology illustrated; interfaces unresolved','P1 + N1 + P2 + N2 + Cu','Series/thermal-parallel role is source-supported; detailed Cu topology, AlN thickness and joining material are authored/unknown. No Ga-In bonding claim for this module.')
add('MODULE_RELEASE','Release one module with four recorded parents','WS_MODULE','module_release','PAIR',['MODULE_RELEASE'],'Four legs and authored copper in fixture','module.PAIRED_TWO.001 on its numbered carrier','One module; parents P1, N1, P2, N2','One new module ID merges four component lineages; no duplicate finished module remains in the jig.')
add('PEM_MOUNT','Carry and seat the module in the cold PEM role','WS_PEM','pem_mount','PAIR',['PEM_PREP','PEM_MOUNT'],'Same module supported outside empty cold-state chamber','Same module seated between labelled contact roles','module.PAIRED_TWO.001 / lower and upper contacts','Transport, cold-open preparation and seating aggregated; actual pressure, fixture fit and safe access are unvalidated.')
add('PEM_WIRE','Connect numbered lead roles and check polarity','WS_PEM','pem_wire','PAIR',['PEM_WIRE'],'Same module seated; leads detached','Lead routing and upper-hot/lower-cold labels illustrated','I, V and heat-flow lead roles','Visual lead routing is authored; this does not establish an electrically valid measurement circuit.')
add('PEM_SEAL','Withdraw hands; close the chamber proxy','WS_PEM','pem_seal','PAIR',['PEM_SEAL'],'Wired module; robot at chamber','Closed visual chamber; vacuum gate not executed','Same module / chamber handle','No vacuum generation, leak test or stability event; closed shell is only a visual state.')
for i,t in enumerate([373,473,573,593]):
 add('BOUNDARY_'+str(t),f'Boundary {i+1}/4: Th {t} K, Tc 293 K','WS_PEM','boundary','PAIR',['PEM_BOUNDARY','PEM_CURRENT','PEM_ACQUIRE','PEM_NEXT'],'Same module; prior boundary history retained',f'Boundary B{i+1} current/acquisition loop illustrated; no numeric readings','module.PAIRED_TWO.001 / B'+str(i+1),'Each boundary aggregates an unspecified current grid, point-by-point I/V/Q or raw voltage acquisition and history preservation. Grid values/count and calibration are unknown; no samples or performance values generated.',boundary_index=i,source_target_Th_K=t,source_target_Tc_K=293)
add('POWERDOWN','Stop output; wait for cooling and release','WS_PEM','powerdown','PAIR',['PEM_POWERDOWN'],'Fourth boundary storyboard complete; same module seated','Drive/heating OFF illustrated; cooling release unresolved','PEM stop target; hands outside chamber','No real drive/heater was active. Trusted cooling/unloading/openability gates are requirements, not observed events.')
add('PEM_UNLOAD','Open, disconnect and support the same module','WS_PEM','pem_unload','PAIR',['PEM_OPEN','PEM_UNLOAD'],'Cold-release gate assumed solely for storyboard','Same module removed; chamber sample volume empty','Module carrier + disconnected lead roles','Venting/opening and unloading are aggregated; no verified contact, clearance or thermal state.')
add('DATA_REVIEW','Review record schema; retain unknown results','WS_DATA','data','PAIR',['PERFORMANCE_ANALYSE'],'Boundary/run/point schema available; no scientific raw values','Power and efficiency remain unknown; calibration not inferred','Same module ID / empty record schema','P=I*V and eta=P/(P+Qc) require actual compatible channels; raw mV is not Qc in W. No maxima or paper performance reproduced.')
add('ARCHIVE','Archive the module and its lineage history','WS_STORAGE','archive','PAIR',['ARCHIVE'],'Same module after illustrated measurement route','One module in measured-route compartment; data marked unexecuted','module.PAIRED_TWO.001; separate leftovers','Measured-route is a storyboard status, not a claim of real measurement. Remaining stock/offcuts stay separate by material/status.')
add('CLEAN','Return tools; seal remnants and clean surfaces','WS_CLEAN','clean','PAIR',['CLEAN'],'Archived module; work surfaces and tooling used in storyboard','Tools returned; inert remnants sealed; empty stations','Dry wipe, tools and closed waste proxies','Cleanup actions aggregated; no hazardous chemical waste or real decontamination operation performed.')
add('RESET','Route closure: one archived module, empty equipment','WS_STORAGE','reset','PAIR',[],'Cleanup chapter complete','All sample-processing stations empty; same module archived','Archived module + returned raw stock','The entire bounded main route is represented. No claim of other paper branches, continuous trajectories or validated execution.')
assert len(frames)==45,len(frames)
# Map all 66 reference occurrences into declared macro frames, including repeated P/N phases.
coverage=[]
for phase,seq in [('P',branch['phases'][0]['operations']),('N',branch['phases'][1]['operations']),('PAIR',branch['phases'][2]['operations']+branch['phases'][3]['operations']+['ARCHIVE','CLEAN'])]:
 for op in seq:
  hits=[f['id'] for f in frames if f['phase']==phase and op in f['evidence']['operation_ids']]
  if op=='MODULE_LEGS':hits=['PLACE_P1','PLACE_N1','PLACE_P2','PLACE_N2']
  if op in ['PEM_BOUNDARY','PEM_CURRENT','PEM_ACQUIRE','PEM_NEXT']:hits=['BOUNDARY_'+str(t) for t in [373,473,573,593]]
  assert hits,(phase,op)
  coverage.append({'occurrence_id':f'{phase}.{op}','operation_id':op,'phase':phase,'frames':hits,'coverage':'illustrated keyframes; grouped actions not separately executed'})
m={'title':'Thermoelectric PAIRED_TWO | Raw materials to one four-leg module','status':'Authored static/kinematic visual storyboard; no executed processing or scientific acquisition','overview':'overview.jpg','coverage':{'reference_operation_occurrences':66,'frames_planned':len(frames),'frames_rendered':0,'branches':['PAIRED_TWO'],'other_paper_branches_claimed':False,'P_legs':2,'N_legs':2,'source_thermal_boundaries':4,'current_points':'unknown; symbolic inner loop explicitly aggregated'},'limitations':['No physics, robot execution, policy, contacts, collision or reachability validation','No milling, sintering, cutting, chemistry, vacuum, thermal or electrical processing','No scientific readings, maximum performance, calibration or successful acquisition generated','One PAIRED_TWO route only; B melt, segmented, contact, computational and literature routes excluded','All object manipulations, poses, travel keyframes and equipment shells are authored proxies','Source P/N envelopes remain unequal; N cut direction unknown; AlN/Cu details and interface dimensions not recovered','Source stage-copy assets are visibility-switched into one evolving lineage, not simultaneous live inventory'], 'frames':frames,'source_scene':'External input THERMO_SCENE: thermoelectric_scene_v3 (not distributed)','source_tasks':URL,'attribution':'Unitree G1 visual meshes: Copyright (c) 2016-2023 HangZhou YuShu TECHNOLOGY CO.,LTD. BSD-3-Clause. See licenses/Unitree_G1_BSD3.txt. Existing first-party laboratory, apparatus and sample proxies reused.'}
(OUT/'frame_manifest.json').write_text(json.dumps(m,indent=2))
(OUT/'loop_coverage.json').write_text(json.dumps({'branch':'PAIRED_TWO','reference_occurrences':coverage,'aggregated_scope':'Per-frame operation_ids identify macro actions combined. No fine motor trajectory reconstructed. Travel uses supported carrier keyframes between changed station docks; transit itself is not rendered or validated.','measurement_loop':{'outer':[{'boundary_id':'B'+str(i+1),'Th_K':t,'Tc_K':293,'same_module_id':'module.PAIRED_TWO.001','current_grid':None,'current_point_count':None,'readings_generated':False,'calibration':'unknown'} for i,t in enumerate([373,473,573,593])],'inner':'PEM_CURRENT -> PEM_ACQUIRE -> preserve per-point ID/history -> PEM_NEXT; repeat over unknown configured grid','claimed_completed_acquisitions':0,'source_fabrication_replicates':'unreported; no independent specimens manufactured at each boundary'}},indent=2))
print(len(frames),'frames;',len(coverage),'reference occurrences mapped')
